# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b47470307a344f8199909bb9bfcb160cf2dddfd42bc7aef591a9250047081f05194e686d27df5b6a7d4bf6fb1b8f17451f28cfa10969a7618d0e0b4360d75ffc

test:
  secret_key_base: ff4748b4c2409cf0f0c2c0e7d2c599fe0ce83c9f41eb4c0324608c4895e6074821e6328d4dd318e2625f487148b3f4920b18e1b51dbcd276988ddc1448417afe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
